// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dog.proto

package proto;

public final class dog {
  private dog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Dog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .tutorial.Dog.Hair hair = 3;</code>
     */
    boolean hasHair();
    /**
     * <code>optional .tutorial.Dog.Hair hair = 3;</code>
     */
    proto.dog.Dog.Hair getHair();
    /**
     * <code>optional .tutorial.Dog.Hair hair = 3;</code>
     */
    proto.dog.Dog.HairOrBuilder getHairOrBuilder();
  }
  /**
   * <pre>
   * 狗
   * </pre>
   *
   * Protobuf type {@code tutorial.Dog}
   */
  public  static final class Dog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Dog)
      DogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dog.newBuilder() to construct.
    private Dog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dog() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 26: {
              proto.dog.Dog.Hair.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = hair_.toBuilder();
              }
              hair_ = input.readMessage(proto.dog.Dog.Hair.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hair_);
                hair_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.dog.internal_static_tutorial_Dog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.dog.internal_static_tutorial_Dog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.dog.Dog.class, proto.dog.Dog.Builder.class);
    }

    public interface HairOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tutorial.Dog.Hair)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string color = 1;</code>
       */
      boolean hasColor();
      /**
       * <code>required string color = 1;</code>
       */
      java.lang.String getColor();
      /**
       * <code>required string color = 1;</code>
       */
      com.google.protobuf.ByteString
          getColorBytes();

      /**
       * <code>optional bool is_length = 2 [default = true];</code>
       */
      boolean hasIsLength();
      /**
       * <code>optional bool is_length = 2 [default = true];</code>
       */
      boolean getIsLength();
    }
    /**
     * <pre>
     * 毛
     * </pre>
     *
     * Protobuf type {@code tutorial.Dog.Hair}
     */
    public  static final class Hair extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tutorial.Dog.Hair)
        HairOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Hair.newBuilder() to construct.
      private Hair(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Hair() {
        color_ = "";
        isLength_ = true;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Hair(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                color_ = bs;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                isLength_ = input.readBool();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.dog.internal_static_tutorial_Dog_Hair_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.dog.internal_static_tutorial_Dog_Hair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.dog.Dog.Hair.class, proto.dog.Dog.Hair.Builder.class);
      }

      private int bitField0_;
      public static final int COLOR_FIELD_NUMBER = 1;
      private volatile java.lang.Object color_;
      /**
       * <code>required string color = 1;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string color = 1;</code>
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            color_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string color = 1;</code>
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int IS_LENGTH_FIELD_NUMBER = 2;
      private boolean isLength_;
      /**
       * <code>optional bool is_length = 2 [default = true];</code>
       */
      public boolean hasIsLength() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bool is_length = 2 [default = true];</code>
       */
      public boolean getIsLength() {
        return isLength_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasColor()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, color_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeBool(2, isLength_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, color_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(2, isLength_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof proto.dog.Dog.Hair)) {
          return super.equals(obj);
        }
        proto.dog.Dog.Hair other = (proto.dog.Dog.Hair) obj;

        if (hasColor() != other.hasColor()) return false;
        if (hasColor()) {
          if (!getColor()
              .equals(other.getColor())) return false;
        }
        if (hasIsLength() != other.hasIsLength()) return false;
        if (hasIsLength()) {
          if (getIsLength()
              != other.getIsLength()) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasColor()) {
          hash = (37 * hash) + COLOR_FIELD_NUMBER;
          hash = (53 * hash) + getColor().hashCode();
        }
        if (hasIsLength()) {
          hash = (37 * hash) + IS_LENGTH_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getIsLength());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static proto.dog.Dog.Hair parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.dog.Dog.Hair parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.dog.Dog.Hair parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.dog.Dog.Hair parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.dog.Dog.Hair parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.dog.Dog.Hair parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.dog.Dog.Hair parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static proto.dog.Dog.Hair parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static proto.dog.Dog.Hair parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static proto.dog.Dog.Hair parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static proto.dog.Dog.Hair parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static proto.dog.Dog.Hair parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(proto.dog.Dog.Hair prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * 毛
       * </pre>
       *
       * Protobuf type {@code tutorial.Dog.Hair}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:tutorial.Dog.Hair)
          proto.dog.Dog.HairOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return proto.dog.internal_static_tutorial_Dog_Hair_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return proto.dog.internal_static_tutorial_Dog_Hair_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  proto.dog.Dog.Hair.class, proto.dog.Dog.Hair.Builder.class);
        }

        // Construct using proto.dog.Dog.Hair.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          color_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          isLength_ = true;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return proto.dog.internal_static_tutorial_Dog_Hair_descriptor;
        }

        @java.lang.Override
        public proto.dog.Dog.Hair getDefaultInstanceForType() {
          return proto.dog.Dog.Hair.getDefaultInstance();
        }

        @java.lang.Override
        public proto.dog.Dog.Hair build() {
          proto.dog.Dog.Hair result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public proto.dog.Dog.Hair buildPartial() {
          proto.dog.Dog.Hair result = new proto.dog.Dog.Hair(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.color_ = color_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.isLength_ = isLength_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof proto.dog.Dog.Hair) {
            return mergeFrom((proto.dog.Dog.Hair)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(proto.dog.Dog.Hair other) {
          if (other == proto.dog.Dog.Hair.getDefaultInstance()) return this;
          if (other.hasColor()) {
            bitField0_ |= 0x00000001;
            color_ = other.color_;
            onChanged();
          }
          if (other.hasIsLength()) {
            setIsLength(other.getIsLength());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasColor()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          proto.dog.Dog.Hair parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (proto.dog.Dog.Hair) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object color_ = "";
        /**
         * <code>required string color = 1;</code>
         */
        public boolean hasColor() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string color = 1;</code>
         */
        public java.lang.String getColor() {
          java.lang.Object ref = color_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              color_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string color = 1;</code>
         */
        public com.google.protobuf.ByteString
            getColorBytes() {
          java.lang.Object ref = color_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            color_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string color = 1;</code>
         */
        public Builder setColor(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          color_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string color = 1;</code>
         */
        public Builder clearColor() {
          bitField0_ = (bitField0_ & ~0x00000001);
          color_ = getDefaultInstance().getColor();
          onChanged();
          return this;
        }
        /**
         * <code>required string color = 1;</code>
         */
        public Builder setColorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          color_ = value;
          onChanged();
          return this;
        }

        private boolean isLength_ = true;
        /**
         * <code>optional bool is_length = 2 [default = true];</code>
         */
        public boolean hasIsLength() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional bool is_length = 2 [default = true];</code>
         */
        public boolean getIsLength() {
          return isLength_;
        }
        /**
         * <code>optional bool is_length = 2 [default = true];</code>
         */
        public Builder setIsLength(boolean value) {
          bitField0_ |= 0x00000002;
          isLength_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool is_length = 2 [default = true];</code>
         */
        public Builder clearIsLength() {
          bitField0_ = (bitField0_ & ~0x00000002);
          isLength_ = true;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tutorial.Dog.Hair)
      }

      // @@protoc_insertion_point(class_scope:tutorial.Dog.Hair)
      private static final proto.dog.Dog.Hair DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new proto.dog.Dog.Hair();
      }

      public static proto.dog.Dog.Hair getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Hair>
          PARSER = new com.google.protobuf.AbstractParser<Hair>() {
        @java.lang.Override
        public Hair parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Hair(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Hair> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Hair> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public proto.dog.Dog.Hair getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HAIR_FIELD_NUMBER = 3;
    private proto.dog.Dog.Hair hair_;
    /**
     * <code>optional .tutorial.Dog.Hair hair = 3;</code>
     */
    public boolean hasHair() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .tutorial.Dog.Hair hair = 3;</code>
     */
    public proto.dog.Dog.Hair getHair() {
      return hair_ == null ? proto.dog.Dog.Hair.getDefaultInstance() : hair_;
    }
    /**
     * <code>optional .tutorial.Dog.Hair hair = 3;</code>
     */
    public proto.dog.Dog.HairOrBuilder getHairOrBuilder() {
      return hair_ == null ? proto.dog.Dog.Hair.getDefaultInstance() : hair_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasHair()) {
        if (!getHair().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getHair());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getHair());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.dog.Dog)) {
        return super.equals(obj);
      }
      proto.dog.Dog other = (proto.dog.Dog) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasHair() != other.hasHair()) return false;
      if (hasHair()) {
        if (!getHair()
            .equals(other.getHair())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasHair()) {
        hash = (37 * hash) + HAIR_FIELD_NUMBER;
        hash = (53 * hash) + getHair().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.dog.Dog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.dog.Dog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.dog.Dog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.dog.Dog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.dog.Dog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.dog.Dog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.dog.Dog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.dog.Dog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.dog.Dog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.dog.Dog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.dog.Dog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.dog.Dog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.dog.Dog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 狗
     * </pre>
     *
     * Protobuf type {@code tutorial.Dog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Dog)
        proto.dog.DogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.dog.internal_static_tutorial_Dog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.dog.internal_static_tutorial_Dog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.dog.Dog.class, proto.dog.Dog.Builder.class);
      }

      // Construct using proto.dog.Dog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHairFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (hairBuilder_ == null) {
          hair_ = null;
        } else {
          hairBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.dog.internal_static_tutorial_Dog_descriptor;
      }

      @java.lang.Override
      public proto.dog.Dog getDefaultInstanceForType() {
        return proto.dog.Dog.getDefaultInstance();
      }

      @java.lang.Override
      public proto.dog.Dog build() {
        proto.dog.Dog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.dog.Dog buildPartial() {
        proto.dog.Dog result = new proto.dog.Dog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (hairBuilder_ == null) {
            result.hair_ = hair_;
          } else {
            result.hair_ = hairBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.dog.Dog) {
          return mergeFrom((proto.dog.Dog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.dog.Dog other) {
        if (other == proto.dog.Dog.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasHair()) {
          mergeHair(other.getHair());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (hasHair()) {
          if (!getHair().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.dog.Dog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.dog.Dog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private proto.dog.Dog.Hair hair_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.dog.Dog.Hair, proto.dog.Dog.Hair.Builder, proto.dog.Dog.HairOrBuilder> hairBuilder_;
      /**
       * <code>optional .tutorial.Dog.Hair hair = 3;</code>
       */
      public boolean hasHair() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .tutorial.Dog.Hair hair = 3;</code>
       */
      public proto.dog.Dog.Hair getHair() {
        if (hairBuilder_ == null) {
          return hair_ == null ? proto.dog.Dog.Hair.getDefaultInstance() : hair_;
        } else {
          return hairBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .tutorial.Dog.Hair hair = 3;</code>
       */
      public Builder setHair(proto.dog.Dog.Hair value) {
        if (hairBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hair_ = value;
          onChanged();
        } else {
          hairBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .tutorial.Dog.Hair hair = 3;</code>
       */
      public Builder setHair(
          proto.dog.Dog.Hair.Builder builderForValue) {
        if (hairBuilder_ == null) {
          hair_ = builderForValue.build();
          onChanged();
        } else {
          hairBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .tutorial.Dog.Hair hair = 3;</code>
       */
      public Builder mergeHair(proto.dog.Dog.Hair value) {
        if (hairBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              hair_ != null &&
              hair_ != proto.dog.Dog.Hair.getDefaultInstance()) {
            hair_ =
              proto.dog.Dog.Hair.newBuilder(hair_).mergeFrom(value).buildPartial();
          } else {
            hair_ = value;
          }
          onChanged();
        } else {
          hairBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .tutorial.Dog.Hair hair = 3;</code>
       */
      public Builder clearHair() {
        if (hairBuilder_ == null) {
          hair_ = null;
          onChanged();
        } else {
          hairBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .tutorial.Dog.Hair hair = 3;</code>
       */
      public proto.dog.Dog.Hair.Builder getHairBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHairFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tutorial.Dog.Hair hair = 3;</code>
       */
      public proto.dog.Dog.HairOrBuilder getHairOrBuilder() {
        if (hairBuilder_ != null) {
          return hairBuilder_.getMessageOrBuilder();
        } else {
          return hair_ == null ?
              proto.dog.Dog.Hair.getDefaultInstance() : hair_;
        }
      }
      /**
       * <code>optional .tutorial.Dog.Hair hair = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.dog.Dog.Hair, proto.dog.Dog.Hair.Builder, proto.dog.Dog.HairOrBuilder> 
          getHairFieldBuilder() {
        if (hairBuilder_ == null) {
          hairBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.dog.Dog.Hair, proto.dog.Dog.Hair.Builder, proto.dog.Dog.HairOrBuilder>(
                  getHair(),
                  getParentForChildren(),
                  isClean());
          hair_ = null;
        }
        return hairBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Dog)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Dog)
    private static final proto.dog.Dog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.dog.Dog();
    }

    public static proto.dog.Dog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Dog>
        PARSER = new com.google.protobuf.AbstractParser<Dog>() {
      @java.lang.Override
      public Dog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.dog.Dog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Dog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Dog_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Dog_Hair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Dog_Hair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tDog.proto\022\010tutorial\"e\n\003Dog\022\014\n\004name\030\001 \002" +
      "(\t\022 \n\004hair\030\003 \001(\0132\022.tutorial.Dog.Hair\032.\n\004" +
      "Hair\022\r\n\005color\030\001 \002(\t\022\027\n\tis_length\030\002 \001(\010:\004" +
      "trueB\014\n\005protoB\003dog"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Dog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Dog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Dog_descriptor,
        new java.lang.String[] { "Name", "Hair", });
    internal_static_tutorial_Dog_Hair_descriptor =
      internal_static_tutorial_Dog_descriptor.getNestedTypes().get(0);
    internal_static_tutorial_Dog_Hair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Dog_Hair_descriptor,
        new java.lang.String[] { "Color", "IsLength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
